version: "3.9"
services:
  web:
    container_name: web
    build: .
    env_file:
      - .env
    environment:
      - "COUCHDB_URL=${COUCHDB_URL}"
      - "ADMIN_USER=${ADMIN_USER}"
      - "ADMIN_PASSWORD=${ADMIN_PASSWORD}"
    restart: unless-stopped

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot


